NAME = metacells-sharpening-vignette

# Taken from the file system rather than from `git ls-files`, because a pattern rule whose
# prerequisites cannot be made is silently skipped, so a notebook which is not committed yet - or a
# stale index - would quietly generate nothing at all.
NOTEBOOK_FILES = $(wildcard *.ipynb)

HTML_FILES = $(patsubst %.ipynb, docs/%.html, $(NOTEBOOK_FILES))

PDF_FILES = $(patsubst %.ipynb, docs/%.pdf, $(NOTEBOOK_FILES))

# The pages of the site which are written by hand rather than generated from a notebook.
SITE_FILES = $(patsubst site/%, docs/%, $(wildcard site/*))

.DEFAULT_GOAL := help

define PRINT_HELP_PYSCRIPT
import re, sys

for line in sys.stdin:
	match = re.match(r'^([a-zA-Z_-]+):.*?## (.*)$$', line)
	if match:
		target, help = match.groups()
		print("%-20s %s" % (target, help))
endef
export PRINT_HELP_PYSCRIPT

help:
	@python3 -c "$$PRINT_HELP_PYSCRIPT" < $(MAKEFILE_LIST)

clean: clean-docs  ## remove all generated documents

clean-docs:
	rm -f $(HTML_FILES) $(PDF_FILES) $(SITE_FILES)

# The tool chain which generates the documents, built here rather than expected to be in the path.
# Every command of the gate names the interpreter it wants out of this directory, so a `jupyter` or
# a `python3` which happens to come first in the path cannot quietly take part - which matters
# because the gate compares generated bytes, and a different `pygments` renders `%%time` as a
# different number of tokens.
#
# The CI server builds this the same way, by calling `make ci_env`, so that what runs there and what
# runs here are installed from the same pinned list. The other environment - the vignette's own,
# which only executing a notebook needs - is `EXECUTE_IN` further down.
#
# These have to be defined here rather than beside their rule, since a target below names the stamp
# as a prerequisite, and `make` expands those as it reads each rule.
CI_ENV = .ci_env
CI_PYTHON = $(abspath $(CI_ENV))/bin/python3
CI_JUPYTER = $(abspath $(CI_ENV))/bin/jupyter

# Fetching the browser also fetches the system libraries it needs, which requires root. The CI
# server has that and asks for it; on a machine where you are not root, install those libraries
# some other way and point `LD_LIBRARY_PATH` at them.
#     make ci_env PLAYWRIGHT_DEPS=--with-deps
PLAYWRIGHT_DEPS =

.PHONY: ci_env
ci_env: $(CI_ENV)/.stamp  ## build the environment which generates the documents

# Nothing runs when the pinned list has not changed, so naming this before every target of the gate
# costs nothing once it is built.
$(CI_ENV)/.stamp: requirements.txt
	python3 -m venv $(CI_ENV)
	$(CI_ENV)/bin/pip install --quiet --requirement requirements.txt
	$(CI_ENV)/bin/playwright install $(PLAYWRIGHT_DEPS) chromium
	touch $@

ci: ci_env test docs check  ## test, generate the documents and check them, as the CI server does

# The scripts which make the notebook out of the steps, and say whether it is current. They need
# neither the vignette installed nor its data, being about notebooks as files.
.PHONY: test
test: $(CI_ENV)/.stamp  ## test the scripts
	$(CI_PYTHON) -m pytest tests

# The CI server has neither the input data nor a way to run the pipeline, so it cannot execute a
# notebook - it can only say that a committed one describes the code it holds. Running the pipeline
# is `make run`, which is done by whoever changed the code.
# Both of these are `steps/Makefile`'s to answer, since it is what says which steps there are and in
# what order; asking it rather than repeating the list keeps there being one definition of it.
.PHONY: check
check: docs  ## check the committed outputs are of the code the notebooks hold now
	$(MAKE) -C steps check PYTHON=$(CI_PYTHON)
	$(CI_PYTHON) scripts/execute_notebooks.py --check $(NOTEBOOK_FILES)

# The code of each cell is developed in `steps`, one script per cell, where a step can be run on its
# own rather than by running the notebook from the top. Which cell holds which step is in the cell's
# own metadata, so the two are checked against each other by name rather than by position.
.PHONY: embed
embed: $(CI_ENV)/.stamp  ## put the code developed in `steps` into the notebook's cells
	$(MAKE) -C steps embed PYTHON=$(CI_PYTHON)

# The vignette's own environment, which executing a notebook is the only thing to need, since that
# runs the pipeline and so needs the eight packages and the Julia they talk to. Everything else
# needs the document tool chain instead, which is `CI_ENV` above - so generating the documents needs
# nothing of the vignette installed.
#
# This default is the conda install. Set it to nothing when installing into the Python and Julia you
# already use, where the environment `make` was started from already is the vignette's:
#     make run EXECUTE_IN=
EXECUTE_IN = conda run --no-capture-output --name metacells-sharpening

# Executing runs the sharpening pipeline, so it is asked for rather than implied by `docs`, and
# even then only the notebooks whose code cells differ from what they were last executed with are
# run. Editing prose therefore regenerates the documents without recomputing anything.
.PHONY: run
run: $(NOTEBOOK_FILES)  ## execute the notebooks whose code changed since they last ran
	$(EXECUTE_IN) python3 scripts/execute_notebooks.py $(NOTEBOOK_FILES)

.PHONY: docs
docs: html pdf site  ## generate all the viewable documents

.PHONY: site
site: $(SITE_FILES)  ## copy the hand written pages of the site

docs/%: site/%
	@mkdir -p docs
	cp $< $@

.PHONY: html
html: $(HTML_FILES)  ## generate the viewable HTML documents

.PHONY: pdf
pdf: $(PDF_FILES)  ## generate the viewable PDF documents

# The notebooks are converted as they are committed, never executed here. Embedding the images and
# clearing the `require.js` and `MathJax` URLs (which otherwise point at a CDN) makes each document
# stand alone, so viewing it needs no network and no other file in this repository.
NBCONVERT_FLAGS = \
    --embed-images \
    --HTMLExporter.require_js_url= \
    --HTMLExporter.mathjax_url= \
    --output-dir docs

docs/%.html: %.ipynb $(CI_ENV)/.stamp
	$(CI_JUPYTER) nbconvert --to html $(NBCONVERT_FLAGS) $<

# A PDF is generated by printing the HTML from a headless chromium, which `playwright` provides.
# That belongs to whoever generates the documents rather than to the vignette's environment, which
# is why installing the vignette does not install it: a reader who only runs the notebook never
# generates a PDF, and the published HTML and PDF are what a reader who does not run it reads.
#
# The chromium stamps the time it generated the PDF into it, which is the only thing that differs
# between two generations of the same notebook. Replacing it with a fixed date of the same length
# leaves every byte offset in the file intact, and makes the generated PDF reproducible, so that
# comparing two generations shows whether anything actually changed.
docs/%.pdf: %.ipynb $(CI_ENV)/.stamp
	$(CI_JUPYTER) nbconvert --to webpdf $(NBCONVERT_FLAGS) $<
	sed -i "s/D:[0-9]\{14\}+00'00'/D:20230101000000+00'00'/g" $@
