NAME = metacells-sharpening-vignette

# Taken from the file system rather than from `git ls-files`, because a pattern rule whose
# prerequisites cannot be made is silently skipped, so a notebook which is not committed yet - or a
# stale index - would quietly generate nothing at all.
NOTEBOOK_FILES = $(wildcard *.ipynb)

HTML_FILES = $(patsubst %.ipynb, docs/%.html, $(NOTEBOOK_FILES))

PDF_FILES = $(patsubst %.ipynb, docs/%.pdf, $(NOTEBOOK_FILES))

# The pages of the site which are written by hand rather than generated from a notebook.
SITE_FILES = $(patsubst site/%, docs/%, $(wildcard site/*))

.DEFAULT_GOAL := help

define PRINT_HELP_PYSCRIPT
import re, sys

for line in sys.stdin:
	match = re.match(r'^([a-zA-Z_-]+):.*?## (.*)$$', line)
	if match:
		target, help = match.groups()
		print("%-20s %s" % (target, help))
endef
export PRINT_HELP_PYSCRIPT

help:
	@python3 -c "$$PRINT_HELP_PYSCRIPT" < $(MAKEFILE_LIST)

clean: clean-docs  ## remove all generated documents

clean-docs:
	rm -f $(HTML_FILES) $(PDF_FILES) $(SITE_FILES)

ci: docs check  ## generate the documents and check them, as the CI server does

# The CI server has neither the input data nor a way to run the pipeline, so it cannot execute a
# notebook - it can only say that a committed one describes the code it holds. Running the pipeline
# is `make run`, which is done by whoever changed the code.
.PHONY: check
check: docs  ## check the committed outputs are of the code the notebooks hold now
	python3 scripts/execute_notebooks.py --check $(NOTEBOOK_FILES)

# How to enter the vignette's own environment, which executing a notebook is the only thing here to
# need: it runs the pipeline, so it needs the eight packages and the Julia they talk to. Everything
# else is the document tool chain and runs in whatever environment `make` was started from, so that
# generating the documents needs nothing of the vignette installed.
#
# This default is the conda install. Set it to nothing when installing into the Python and Julia you
# already use, where the environment `make` was started from already is the vignette's:
#     make run EXECUTE_IN=
EXECUTE_IN = conda run --no-capture-output --name metacells-sharpening

# Executing runs the sharpening pipeline, so it is asked for rather than implied by `docs`, and
# even then only the notebooks whose code cells differ from what they were last executed with are
# run. Editing prose therefore regenerates the documents without recomputing anything.
.PHONY: run
run: $(NOTEBOOK_FILES)  ## execute the notebooks whose code changed since they last ran
	$(EXECUTE_IN) python3 scripts/execute_notebooks.py $(NOTEBOOK_FILES)

.PHONY: docs
docs: html pdf site  ## generate all the viewable documents

.PHONY: site
site: $(SITE_FILES)  ## copy the hand written pages of the site

docs/%: site/%
	@mkdir -p docs
	cp $< $@

.PHONY: html
html: $(HTML_FILES)  ## generate the viewable HTML documents

.PHONY: pdf
pdf: $(PDF_FILES)  ## generate the viewable PDF documents

# The notebooks are converted as they are committed, never executed here. Embedding the images and
# clearing the `require.js` and `MathJax` URLs (which otherwise point at a CDN) makes each document
# stand alone, so viewing it needs no network and no other file in this repository.
NBCONVERT_FLAGS = \
    --embed-images \
    --HTMLExporter.require_js_url= \
    --HTMLExporter.mathjax_url= \
    --output-dir docs

docs/%.html: %.ipynb
	jupyter nbconvert --to html $(NBCONVERT_FLAGS) $<

# A PDF is generated by printing the HTML from a headless chromium, which `playwright` provides.
# That belongs to whoever generates the documents rather than to the vignette's environment, which
# is why installing the vignette does not install it: a reader who only runs the notebook never
# generates a PDF, and the published HTML and PDF are what a reader who does not run it reads.
#
# The chromium stamps the time it generated the PDF into it, which is the only thing that differs
# between two generations of the same notebook. Replacing it with a fixed date of the same length
# leaves every byte offset in the file intact, and makes the generated PDF reproducible, so that
# comparing two generations shows whether anything actually changed.
docs/%.pdf: %.ipynb
	jupyter nbconvert --to webpdf $(NBCONVERT_FLAGS) $<
	sed -i "s/D:[0-9]\{14\}+00'00'/D:20230101000000+00'00'/g" $@
